import React from 'react'

export default function PrivacyModal({onClose, onEnableStrict, onManageOverrides}){
  return (
    <div className="modal-overlay">
      <div className="modal">
        <h3>Privacy mode</h3>
        <p>Strict privacy uses a sandboxed iframe to reduce third-party tracking. This may limit playback, autoplay, or some embed features (ads will be blocked in many cases but video playback might be affected in some browsers).</p>
        <p style={{color:'#6b7280'}}>Try strict privacy to reduce tracking. If a video won't play, disable strict privacy for that video.</p>
        <p style={{color:'#6b7280',fontSize:13}}>You may also see console messages about Content-Security-Policy, partitioned cookies, feature-policy / "Skipping unsupported feature name" messages, or "unreachable code" from embedded YouTube scripts — these are generated by third-party providers and are usually harmless. To reduce noisy feature-policy messages, use the app's click-to-load player (the iframe only loads after you click) or disable strict privacy for a particular video if playback fails. You can persist per-video privacy overrides so the choice is remembered across sessions in your browser.</p>
        <div style={{display:'flex',gap:8,marginTop:12}}>
          <button className="cta" onClick={()=>{ onEnableStrict(true); onClose() }}>Use strict privacy</button>
          <button className="cta ghost" onClick={onClose}>Close</button>
          <button className="small" onClick={()=>{ onManageOverrides && onManageOverrides() }}>Manage overrides</button>
        </div>
      </div>
    </div>
  )
}